# Generated by Django 4.1.3 on 2022-11-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchises',
            fields=[
                ('title', models.CharField(db_column='Title', max_length=45, primary_key=True, serialize=False)),
                ('sphere', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'franchises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lanquages',
            fields=[
                ('lanquage', models.CharField(db_column='Lanquage', max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lanquages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OriginalWords',
            fields=[
                ('wordid', models.AutoField(db_column='wordID', primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=50, null=True)),
                ('transcryption', models.CharField(blank=True, max_length=100, null=True)),
                ('special_information', models.CharField(blank=True, max_length=200, null=True)),
                ('franchise', models.ForeignKey(db_column='franchise', on_delete=django.db.models.deletion.PROTECT, to='glossary.franchises')),
                ('original_lanquage', models.ForeignKey(blank=True, db_column='original_lanquage', null=True, on_delete=django.db.models.deletion.PROTECT, to='glossary.lanquages')),
            ],
            options={
                'db_table': 'original_words',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LanqFran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.ForeignKey(blank=True, db_column='franchise', null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.franchises')),
                ('lanquage', models.ForeignKey(blank=True, db_column='lanquage', null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.lanquages')),
            ],
        ),
        migrations.CreateModel(
            name='UkrTrans',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('transcryption', models.CharField(blank=True, max_length=100, null=True)),
                ('word', models.CharField(max_length=45)),
                ('special_information', models.CharField(blank=True, max_length=450, null=True)),
                ('franchise', models.ForeignKey(db_column='franchise', on_delete=django.db.models.deletion.PROTECT, to='glossary.franchises')),
                ('original', models.OneToOneField(db_column='original_ID', on_delete=django.db.models.deletion.PROTECT, to='glossary.originalwords')),
            ],
            options={
                'db_table': 'ukr_trans',
                'managed': True,
                'unique_together': {('word_id', 'original')},
            },
        ),
    ]
